package net.flipper.tools.drawtool.api.model

import kotlinx.collections.immutable.ImmutableList
import kotlin.time.Instant

/**
 * A Draw tool status stored in the local collection of a BUSY Bar.
 *
 * [id] is 16 lowercase hex characters generated by the library. [updatedAt] is
 * the last save time at second resolution and doubles as the status version for
 * last-write-wins conflict resolution during sync. [files] covers every file of
 * the status except `project.json`, which the library owns.
 */
data class DrawToolStatus(
    val id: String,
    val updatedAt: Instant,
    val files: ImmutableList<DrawToolStoredFile>
) {
    /** The `preview.png` the status list shows, if the status has one. */
    val preview: DrawToolStoredFile? by lazy {
        files.firstOrNull { storedFile -> storedFile.type == DrawToolFileType.PREVIEW }
    }
}
