version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    groups:
      all-gradle-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1
    rebase-strategy: "disabled"
    groups:
      all-actions:
        patterns:
          - "*"
