flipper.major_version=0.1
# Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Gradle
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.isolated-projects=true
org.gradle.jvmargs=-Xmx8G -XX:+UseParallelGC -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx8G"
org.gradle.parallel=true
org.gradle.tooling.parallel=true
# Kotlin
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
kotlin.code.style=official
kotlin.incremental=true
# Gradle Project
## Android
klibs.android.sdk.min=26
klibs.android.sdk.target=36
klibs.android.sdk.compile=36
## Java
klibs.java.source=8
klibs.java.target=21
klibs.java.ktarget=21
## Project
klibs.project.name=busylib.kmp
klibs.project.group=net.flipper.busylib.kmp
klibs.project.version.string=local
klibs.project.version.code=1
klibs.project.description=Kotlin Multiplatform BUSY Bar library
klibs.project.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com, LionZXY|Nikita Kulikov|n@kulikov.uk, Programistich|Oleksii Dzhos|me@programistich.com
klibs.project.url=https://github.com/busy-app/busylib-kmp
## Publish
klibs.publish.repo.name=busylib.kmp
klibs.publish.groupId=net.flipper.busylib.kmp
klibs.publish.description=Kotlin Multiplatform BUSY Bar library
klibs.publish.repo.org=TODO
klibs.publish.name=busylib.kmp
klibs.publish.license=TODO
klibs.publish.developers=makeevrserg|Makeev Roman|makeevrserg@gmail.com, LionZXY|Nikita Kulikov|n@kulikov.uk, Programistich|Oleksii Dzhos|me@programistich.com
org.jetbrains.compose.experimental.macos.enabled=true
## https://youtrack.jetbrains.com/issue/KT-85598
kotlin.native.binary.gcMutatorsCooperate=false
