rootProject.name = "BusyStatusBar"
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    includeBuild("build-logic")

    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
    }
}

include(
    ":instances:bsb",
    ":instances:bsb-wear",
    ":instances:videotest",
    ":instances:desktop",

    ":components:core:di",
    ":components:core:activityholder",
    ":components:core:apppackage",
    ":components:core:log",
    ":components:core:ktx",
    ":components:core:ktx-compose",
    ":components:core:data",
    ":components:core:build-konfig",
    ":components:core:focus-display",
    ":components:core:exoplayer-fade",
    ":components:core:network",
    ":components:core:vibrator",
    ":components:core:ui:decompose",
    ":components:core:ui:lifecycle",
    ":components:core:ui:appbar",
    ":components:core:ui:button",
    ":components:core:ui:sheet",
    ":components:core:ui:dialog",
    ":components:core:ui:picker",
    ":components:core:ui:option",
    ":components:core:ui:timeline",
    ":components:core:ui:card-frame",
    ":components:core:ui:res-preview",
    ":components:core:ui:autosizetext",
    ":components:core:ui:text",
    ":components:core:trusted-clock:api",
    ":components:core:trusted-clock:google",
    ":components:core:trusted-clock:truetime",
    ":components:core:trusted-clock:kotlinx",

    ":components:bsb:core:theme",
    ":components:bsb:core:markdown",
    ":components:bsb:core:files",
    ":components:bsb:core:ui:icons",
    ":components:bsb:core:ui:strings",
    ":components:bsb:core:ui:components",
    ":components:bsb:core:ui:dialog",

    ":components:bsb:dao:api",
    ":components:bsb:dao:impl",

    ":components:bsb:root:api",
    ":components:bsb:root:impl",
    ":components:bsb:preference:api",
    ":components:bsb:preference:impl",
    ":components:bsb:cloud:api",
    ":components:bsb:cloud:impl",
    ":components:bsb:deeplink:api",
    ":components:bsb:deeplink:impl",
    ":components:bsb:inappnotification:api",
    ":components:bsb:inappnotification:impl",
    ":components:bsb:sound:impl",
    ":components:bsb:liveactivity:api",

    ":components:bsb:analytics:shake2report:api",
    ":components:bsb:analytics:shake2report:impl",
    ":components:bsb:analytics:shake2report:noop",
    ":components:bsb:analytics:timer:api",
    ":components:bsb:analytics:timer:impl",
    ":components:bsb:analytics:filelogging:api",
    ":components:bsb:analytics:filelogging:noop",
    ":components:bsb:analytics:filelogging:impl",
    ":components:bsb:analytics:metric:api",
    ":components:bsb:analytics:metric:posthog",
    ":components:bsb:analytics:metric:noop",

    ":components:bsb:appblocker:core:api",
    ":components:bsb:appblocker:core:impl",
    ":components:bsb:appblocker:filter:api",
    ":components:bsb:appblocker:filter:impl",
    ":components:bsb:appblocker:permission:api",
    ":components:bsb:appblocker:permission:impl",
    ":components:bsb:appblocker:screen",
    ":components:bsb:appblocker:stats:api",
    ":components:bsb:appblocker:stats:impl",
    ":components:bsb:appblocker:splash:api",
    ":components:bsb:appblocker:splash:impl",
    ":components:bsb:appblocker:notification:impl",

    ":components:bsb:auth:common",
    ":components:bsb:auth:main:impl",
    ":components:bsb:auth:main:api",
    ":components:bsb:auth:main:impl",
    ":components:bsb:auth:login:api",
    ":components:bsb:auth:login:impl",
    ":components:bsb:auth:signup:api",
    ":components:bsb:auth:signup:impl",
    ":components:bsb:auth:confirmpassword:api",
    ":components:bsb:auth:confirmpassword:impl",
    ":components:bsb:auth:expiredsession:api",
    ":components:bsb:auth:expiredsession:impl",
    ":components:bsb:auth:otp:element:api",
    ":components:bsb:auth:otp:element:impl",
    ":components:bsb:auth:otp:screen:api",
    ":components:bsb:auth:otp:screen:impl",
    ":components:bsb:auth:within:common",
    ":components:bsb:auth:within:main:api",
    ":components:bsb:auth:within:main:impl",
    ":components:bsb:auth:within:oauth:api",
    ":components:bsb:auth:within:oauth:data",
    ":components:bsb:auth:within:oauth:impl",
    ":components:bsb:auth:within:onetap:api",
    ":components:bsb:auth:within:onetap:impl",
    ":components:bsb:auth:within:passkey:api",
    ":components:bsb:auth:within:passkey:impl",
    ":components:bsb:auth:principal:api",
    ":components:bsb:auth:principal:impl",

    ":components:bsb:profile:common",
    ":components:bsb:profile:main:api",
    ":components:bsb:profile:main:impl",
    ":components:bsb:profile:passkeyview:api",
    ":components:bsb:profile:passkeyview:impl",

    ":components:bsb:debug:version-element:api",
    ":components:bsb:debug:version-element:impl",
    ":components:bsb:debug:version-element:noop",
    ":components:bsb:debug:screen:api",
    ":components:bsb:debug:screen:impl",
    ":components:bsb:debug:screen:noop",

    ":components:bsb:timer:common",
    ":components:bsb:timer:setup:api",
    ":components:bsb:timer:setup:impl",
    ":components:bsb:timer:main:api",
    ":components:bsb:timer:main:impl",
    ":components:bsb:timer:done:api",
    ":components:bsb:timer:done:impl",
    ":components:bsb:timer:background:api",
    ":components:bsb:timer:background:impl",
    ":components:bsb:timer:active:api",
    ":components:bsb:timer:active:impl",
    ":components:bsb:timer:delayed-start:api",
    ":components:bsb:timer:delayed-start:impl",
    ":components:bsb:timer:cards:api",
    ":components:bsb:timer:cards:impl",
    ":components:bsb:timer:syncservice:api",
    ":components:bsb:timer:syncservice:firebase:api",
    ":components:bsb:timer:syncservice:firebase:impl",
    ":components:bsb:timer:syncservice:firebase:noop",
    ":components:bsb:timer:syncservice:cloud",
    ":components:bsb:timer:syncservice:looped",
    ":components:bsb:timer:syncservice:polling",
    ":components:bsb:timer:state-builder",
    ":components:bsb:timer:notification:api",
    ":components:bsb:timer:notification:android",
    ":components:bsb:timer:notification:wearos",
    ":components:bsb:timer:notification:common",
    ":components:bsb:timer:controller",
    ":components:bsb:timer:vibration:impl",
    ":components:bsb:timer:dao:shared",
    ":components:bsb:timer:dao:internal",
    ":components:bsb:timer:dao:mapper",

    ":components:bsb:music:equalizer:api",
    ":components:bsb:music:equalizer:impl",
    ":components:bsb:music:equalizer:sample",
    ":components:bsb:music:player:api",
    ":components:bsb:music:player:impl",
    ":components:bsb:music:choice:api",
    ":components:bsb:music:choice:impl",
    ":components:bsb:music:storage:api",
    ":components:bsb:music:storage:impl",

    ":components:bsb:video:common",
    ":components:bsb:video:orchestrator:api",
    ":components:bsb:video:orchestrator:impl",
    ":components:bsb:video:ui",

    ":components:bsb:wear:bridge:messenger:api",
    ":components:bsb:wear:bridge:messenger:impl",
    ":components:bsb:wear:bridge:messenger:common",
    ":components:bsb:wear:bridge:messenger:noop",
    ":components:bsb:wear:bridge:syncservice:api",
    ":components:bsb:wear:bridge:syncservice:wear",
    ":components:bsb:wear:bridge:syncservice:android",
    ":components:bsb:wear:bridge:syncservice:noop",

    ":components:bsb:device:bridge:config:api",
    ":components:bsb:device:bridge:config:impl",
    ":components:bsb:device:bridge:connectionbuilder:api",
    ":components:bsb:device:bridge:connectionbuilder:impl",
    ":components:bsb:device:bridge:device:common:api",
    ":components:bsb:device:bridge:device:bsb:api",
    ":components:bsb:device:bridge:device:bsb:impl",
    ":components:bsb:device:bridge:orchestrator:api",
    ":components:bsb:device:bridge:orchestrator:impl",
    ":components:bsb:device:bridge:service:api",
    ":components:bsb:device:bridge:service:impl",
    ":components:bsb:device:bridge:transport:mock:api",
    ":components:bsb:device:bridge:transport:mock:impl",
    ":components:bsb:device:bridge:transport:common:api",
    ":components:bsb:device:bridge:transport:common:impl",
    ":components:bsb:device:bridge:transport:ble:api",
    ":components:bsb:device:bridge:transport:ble:impl",
    ":components:bsb:device:bridge:sample:shared",
    ":components:bsb:device:bridge:sample:android",
    ":components:bsb:device:bridge:transportconfigbuilder:api",
    ":components:bsb:device:bridge:transportconfigbuilder:impl",
    ":components:bsb:device:bridge:feature:common:api",
    ":components:bsb:device:bridge:feature:provider:api",
    ":components:bsb:device:bridge:feature:provider:impl",
    ":components:bsb:device:bridge:feature:rpc:api",
    ":components:bsb:device:bridge:feature:rpc:impl",
    ":components:bsb:device:bridge:feature:info:api",
    ":components:bsb:device:bridge:feature:info:impl",
    ":components:bsb:device:bridge:feature:wifi:api",
    ":components:bsb:device:bridge:feature:wifi:impl",
    ":components:bsb:device:bridge:feature:link:api",
    ":components:bsb:device:bridge:feature:link:impl",
    ":components:bsb:device:bridge:feature:sync:impl",
    ":components:bsb:device:bridge:feature:battery:api",
    ":components:bsb:device:bridge:feature:battery:impl",
    ":components:bsb:device:bridge:feature:screen-streaming:api",
    ":components:bsb:device:bridge:feature:screen-streaming:impl",
    ":components:bsb:device:bridge:feature:screen-streaming:compose",
    ":components:bsb:device:bridge:feature:firmware-update:api",
    ":components:bsb:device:bridge:feature:firmware-update:impl",

    ":components:bsb:device:firstpair:connection:api",
    ":components:bsb:device:firstpair:connection:impl",
    ":components:bsb:device:firstpair:screen:api",
    ":components:bsb:device:firstpair:screen:impl",
    ":components:bsb:device:entrypoint:api",
    ":components:bsb:device:entrypoint:impl",
    ":components:bsb:device:dashboard:api",
    ":components:bsb:device:dashboard:impl",
    ":components:bsb:device:fw-update:api",
    ":components:bsb:device:fw-update:impl",
    ":components:bsb:device:screen-streaming:api",
    ":components:bsb:device:screen-streaming:impl",
    ":components:bsb:device:alreadylinked:api",
    ":components:bsb:device:alreadylinked:impl",
    ":components:bsb:device:promo:api",
    ":components:bsb:device:promo:impl",

    ":components:bsb:device:wifi:help:api",
    ":components:bsb:device:wifi:help:impl",
    ":components:bsb:device:wifi:list:api",
    ":components:bsb:device:wifi:list:impl",
    ":components:bsb:device:wifi:auth:api",
    ":components:bsb:device:wifi:auth:impl",
    ":components:bsb:device:finishsetup:api",
    ":components:bsb:device:finishsetup:impl",

    ":detekt"
)