name: "detekt-validation"
on:
  workflow_call:
jobs:
  detekt:
    name: "Check project by detekt"
    runs-on: [ self-hosted, Linux, Android ]
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Set up JDK 1.17
        uses: ./.github/actions/setup-java
      - name: Give gradle permission
        run: chmod +x gradlew
      - name: detekt
        uses: gradle/gradle-build-action@v3
        with:
          arguments: detekt