name: Detekt
on:
  workflow_call:
jobs:
  detekt:
    name: Check project by detekt
    runs-on: [ self-hosted, Linux, Android ]
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
      - name: Set up JDK 21
        uses: ./.github/actions/setup-java
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Run detekt
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
        with:
          arguments: detekt
